spring.application.name=rag
file.upload-dir=temp-uploads

minio.url=http://localhost:9000
minio.access-key=wQbv1XM7WQ2TCeLeDiYf
minio.secret-key=pTId0W9PbTknQPtUwBdOuqsyYHvSQqCtcXhGpvnb

elasticsearch.host=http://localhost:9200
elasticsearch.index=documents